# -*- coding: utf-8 -*-
"""Kalman_Filter

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Lp-AHlJVWlVURUdNTDIrZCqdwpAg5zGW
"""

import numpy as np
import matplotlib.pyplot as plt
!pip install yfinance
import yfinance as yf


def load_log_prices(ticker,start,end):
  """
  Downloads closing prices and returns natural log.

  Log-prices are used because the constant_velocity model assumes additive
  linear motion, while raw price data compounds multiplicatevely. Taking the log
  converts exponential growth into a linear function the model can track
  """

  data = yf.download(ticker, start=start, end=end )
  prices = data["Close"].values.flatten()
  return np.log(prices)


def Kalman(log_prices,q_pos,q_vel, R_var,dt=1.0):
  """
  Constant-velocity Kalman filter on a 1-D series.

  State = [level,velocity]. Only the level is measured; velocity is inferred
  through the covariance coupling in P.

  Returns:(positions,velocities,normalized_innovations)
  """

  n = len(log_prices)

  pos_estimates = []
  vel_estimates = []
  norm_innov = []

  # State: [log-price level, daily drift]. Start at the first observed price with
  # zero assumed drift.

  x = np.array([[log_prices[0]],
                [0.0]])

  # Initial uncertatinty: modest on level (already know the first price)
  # smaller on drift. Converges to steady state within ~20 steps regardless.

  P = np.array([[1e-4, 0.0],
                [0.0, 1e-6]])

  # Process noise: how much level and drift are allowed to wander per step.
  # These are the tuned parameters (see sweep_Q)

  Q = np.array([[q_pos, 0.0],
                [0.0, q_vel]])
  H = np.array([[1,0]]) # measurement maps state -> level only
  R = np.array([[R_var]]) # measurement-noise variance (from data)
  F = np.array([[1.0,dt], # constant-velocity transition:
                [0.0, 1.0]]) # level += velocity*dt, velocity unchanged.

  for i in range(n):
    z = np.array(([[log_prices[i]]]))

    # --- Predict: project state and inflate uncertainty ---
    x_pred = F @ x
    P_pred = F @ P @ F.T + Q

    # --- Update: fold in the measurement ---
    y= z - H @ x_pred               #innovation: prediction error
    S= H @ P_pred @ H.T + R         #innovation variance (expected error size)
    norm_innov.append(y[0,0]/np.sqrt(S[0,0])) # for whiteness testing


    K= P_pred @ H.T @ np.linalg.inv(S) # gain: how far to trust the measurement
    x= x_pred + K @ y                  # corrected state
    P= (np.eye(2)- K @ H) @ P_pred     # reduce uncertainty

    pos_estimates.append(x[0,0])
    vel_estimates.append(x[1,0])

  return pos_estimates, vel_estimates, norm_innov

def diagnostics(norm_innov, burn=20):
  """
  Innovation-whiteness test.

  A correctly specified filter yields innovations that are standard normal
  (std ~ 1) and uncorrelated (autocorr~0). First 'burn' steps are dropped as
  start-up transient.
  """

  ni = np.array(norm_innov[burn:])
  return{
    "std": np.std(ni),
    "mean": np.mean(ni),
    "autocorr": np.corrcoef(ni[:-1],ni[1:])[0,1]
  }

def sweep_Q(log_prices, R_var, q_pos_grid, q_vel_grid,burn=20):
  """
  Grid-search Q, prints std and autocorr for each setting.

  Used to show no single value of Q calibrates both the standard deviation
  approaching 1 (std~1) and the autocorrelation approaching 0 (autocorr~0)
  """
  for q_pos in q_pos_grid:
    for q_vel in q_vel_grid:
      _,_,ninv = Kalman(log_prices,q_pos,q_vel,R_var)
      d=diagnostics(ninv, burn)
      print(
          f"({q_pos:.0e},{q_vel:.0e})"
          f" std = {d['std']:.3f} "
          f" autocorr={d['autocorr']:.3f}"
      )


#---------- Driver ----------
log_prices = load_log_prices("QQQ","2019-01-01","2025-01-01")

#measurement noise = variance of daily log - returns
R_var = np.std(np.diff(log_prices))**2
n=len(log_prices)
burn=20

print("Q sweep:")
sweep_Q(log_prices, R_var, [1e-6,1e-5,1e-4],[1e-9,1e-8,1e-7,1e-6])

# Final run at the chosen setting (prioritize readeable drift over whiteness).
pos_estimates,vel_estimates,norm_innov = Kalman(log_prices,1e-5,1e-8,R_var)
ni=np.array(norm_innov[burn:])
print("Diagnostics:", diagnostics(norm_innov))


#---------- Plots ----------

# Innovations Histogram
plt.figure(figsize=(10,5))
plt.hist(ni, bins=50, density=True, alpha=0.6, label='Normalized Innovations')
xs = np.linspace(-5, 5, 200)
plt.plot(xs, (1/np.sqrt(2*np.pi))*np.exp(-xs**2/2),'r-',lw=2,label='N(0,1)')
plt.title('Normalized Innovations vs Standard Normal - QQQ')
plt.xlabel('Normalized Innovations');plt.ylabel('Density');plt.legend()
plt.savefig('stage3_innovations_hist.png',dpi=150, bbox_inches = 'tight')
plt.show()

# Daily drift plot
plt.figure(figsize=(10,5))
plt.axhline(0,color = 'k', lw=0.5)
plt.plot(range(burn,n), vel_estimates[burn:],'b-', label= 'Estimated Drift')
plt.title('Kalman-Estimated Daily Drift of QQQ (2019-2025)')
plt.legend(); plt.xlabel('Trading Day'); plt.ylabel('Estimated drift (log-return per day)');
plt.savefig('stage3_drift_daily.png', dpi=150, bbox_inches='tight')
plt.show()


# Annualized drift plot
plt.figure(figsize=(10,5))
plt.plot(range(burn,n), np.array(vel_estimates[burn:])*252, 'b-', label='Annualized drift')
plt.axhline(0, color= 'k', lw= 0.5)
plt.title('Kalman-Estimated Annualized Drift of QQQ (2019-2025)')
plt.legend();plt.ylabel('Annualized drift');plt.xlabel('Trading Day')
plt.savefig('stage3_drift_annualized.png', dpi=150, bbox_inches='tight')
plt.show()


# QQQ data Kalman Filtered
plt.figure(figsize=(10,5))
plt.plot(log_prices, 'k-', alpha=0.5, label='Observed Log Price')
plt.plot(pos_estimates, 'b-', label = 'Kalman Estimate')
plt.title('QQQ Log-Price vs. Kalman Trend Estimate (2019 - 2025)')
plt.legend(); plt.xlabel('Trading Day'); plt.ylabel('Log Price')
plt.savefig('stage3_qqq_filtered.png', dpi=150, bbox_inches='tight')
plt.show()

